# Generated by Django 4.2.21 on 2025-05-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateField()),
                ('limit_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videoproject')),
            ],
        ),
        migrations.CreateModel(
            name='TagConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
                ('video_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videoproject')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAgreementOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.businessagreement')),
                ('video_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videoproject')),
            ],
        ),
        migrations.AddField(
            model_name='businessagreement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
